### ISSUE TITLE
ERB trim_mode

### ISSUE THREAD

**Issue by kshpytsya** [criteo/consul-templaterb#21]
Is there any chance to enable `-%>` syntax for new-line omission in templates? 
Changing
https://github.com/criteo/consul-templaterb/blob/55355614f868ef73a58baf68e69324ec9244de84/lib/consul/async/consul_template.rb#L172
to
```ruby
result = ERB.new(tpl, nil, '-').result(binding)
```
seems to do the trick for me.

However, it looks like something like the [following](https://github.com/imaharu/rubyhackchallenge/blob/84a4035eaf0b5276941c82c865d8b9c100559c0a/rubyhackchallenge/spec/ruby/library/erb/fixtures/classes.rb#L3-L7
) may be needed to support different Ruby versions.

**Comment by pierresouchay** [comment]
@kshpytsya Sure, provide a PR to do so.

All of our templates are checked each time by our unit tests, as long as you do not break anything.

If you can provide compatibility with several ruby versions, that's even better.

**Comment by pierresouchay** [comment]
@kshpytsya Ok with this implementation ? => https://github.com/criteo/consul-templaterb/commit/0ef9abd77c780532b8a615b38af879e60bc9278d ?

**Comment by pierresouchay** [comment]
@kshpytsya included in version 1.5.0
