### ISSUE TITLE
Helpers to list all templates being rendered

### ISSUE THREAD

**Issue by kamaradclimber** [criteo/consul-templaterb#52]
I'd like to build a small collection of templates and have a index.html page that would list links to all templates being rendered.

It seems there is no endpoint in the template API to access list of templates.
Could we consider adding one?

**Comment by pierresouchay** [comment]
yes, [template_info](https://github.com/criteo/consul-templaterb/blob/master/TemplateAPI.md#template_info) return information about current template being rendered, it would be ok to have a way to list those objects if you think it might be useful

**Comment by pierresouchay** [comment]
Implemented into #53
