### ISSUE TITLE
Question: multiple unrelated consul endpoints

### ISSUE THREAD

**Issue by kshpytsya** [criteo/consul-templaterb#58]
Is interaction with multiple unrelated consul endpoints supported and if not, would such a feature be within the scope of this project?

My specific use-case that I want to implement with `consul-templaterb` is replacement for Prometheus' own intentionally limited (and possibly buggy) `consul_sd`. Due to the stance of the Prometheus project developers that if one needs anything more complex than they have already implemented, one should use some external tooling to produce a file with metrics endpoints and their settings, `consul-templaterb` seems like a great fit. But... my setup involves multiple unrelated (i.e. not federated using datacenters mechanism) consul clusters. The set of additional consul clusters is dynamic and is obtained from the main consul cluster. Specifically, consul agents connected to those clusters are registered as services in the main consul cluster.

Of course, I could try cascading multiple instances of `consul-templaterb` but that seems to be a tricky kludge.

**Comment by pierresouchay** [comment]
@kshpytsya Well, for now I would like to avoid this to avoid over complexifying the codebase as it would break the existing templates (aka, a way to specify a particular instance of a given cluster).

Furthermore, having one single agent allow to be broken when the while cluster is down (and to have a particular behavior in that case), but what if 1 cluster is broken and not the other ones, mixing several clusters in a single template?

So, unless you come with a nice PR dealing with those issues, I would say it is probably not a priority on our side :-)

We are already doing in very large production what you describe, but we try - as much as possible - to have clear separation between datacenters for instance to reduce the risk of a big resilience issue (you might have a look to https://medium.com/criteo-labs/mixing-observability-with-service-discovery-2bb8909e8530 on how we are doing this).

As a side note, as you already noticed, it is still possible to mix several instances of consul-templaterb on a single machine (and ask your prometheus - if you want to do so - to use several files and use all those files to have a single instance fetching data from various clusters). It is even possible to have a single template source using different parameters (see https://github.com/criteo/consul-templaterb/#generate-multiple-templates )

**Comment by kshpytsya** [comment]
Thank you for your elaborate answer. It looks I am just going to implement the functionality I need in my language of choice, namely Python.

**Comment by pierresouchay** [comment]
Hello @kshpytsya,

After some thinking, and a in depth look at the code, the patch to achieve what you wanted to do is not that difficult, so I implemented it in Release 1.26.0.

There is an advanced example on how doing it here:
https://github.com/criteo/consul-templaterb/blob/master/samples/all_services_multi_agents.txt.erb

I hope it will help you, but most methods do now support to add `agent: http://address_of_consul_or_vaul:port`, so you can federate multiple clusters if you want.

See https://github.com/criteo/consul-templaterb/blob/master/TemplateAPI.md for more information.
