### ISSUE TITLE
Getting timestamp in templates

### ISSUE THREAD

**Issue by ishergin** [criteo/consul-templaterb#63]
Hello!

I have to get timestamp of last template changing and might use Time.now.to_i. However I get realtime changing timestamp instead timestamp of last template changing. Consul-template allows use  `timestamp "unix"` and there is no similar problem. Timestamp requires for SOA records :(

**Comment by pierresouchay** [comment]
In the stats endpoint, you have the x_consul_index which is strictly incrementin when data is changing. The value is an uint64 in Consul, so you might have to take care about boundaries, but you might use it. Timestamp might be computed but it is risky: it depends on the clock of machine, so if you run it on several different machines (eg: to have redundancy to generate your DNS records, it will be different across machines while x_consul_index will not.

See:
https://github.com/criteo/consul-templaterb/blob/master/TemplateAPI.md#accessing-to-statistics-to-monitor-your-cluster

**Comment by ishergin** [comment]
Thanks! I think it is ok as a temporary solution.
I have time synchronisation and there is no difference between machines for timestamp in seconds.

**Comment by pierresouchay** [comment]
Even with time sync, there is no mechanism to ensure all clients have the same timestamp :(
Consul provides consistency with x-consul-index, but not with timestamp unfortunately. One of the consul-templaterb might receive it at 10:32:24 while the other might receive it at 10:33:07 for instance.
However, both will receive the same index

**Comment by pierresouchay** [comment]
@ishergin As I said, this will give you unpredictable results (just consider that launching consul-templaterb 2 times will give you 2 different results), still if you want to do it, you can that way:

```erb
<%
  @my_last_time = Time.now.utc unless @my_last_time
  # you can use any endpoint you want, ie: service('consul') for instance
  val = nodes()
  new_idx = val.endpoint.x_consul_index
  @my_last_time = Time.now.utc if @my_last_idx != new_idx
  @my_last_idx = new_idx
%>
Last update: <%= @my_last_time.to_i %> (<%= @my_last_time %>), X-Consul-Index: <%= new_idx %>
```

It will create a stable value with the first timestamp of modification so mimicking consul-template. But remember this is:
 * not stable across runs (while x_consul_index is): run it 2 times, you'll get different timestamps
 * not stable across machines - even in sync with NTP

**Comment by pierresouchay** [comment]
@ishergin Did you find this answer useful?

I added a full sample in https://github.com/criteo/consul-templaterb/commit/71c767c041f5a0858bfa16ae64b19f98ea561d3f

I don't see any way implementing it in a reliable way, so feel free to re-open if you have ideas or are not satisfied with the answer

Best
