### ISSUE TITLE
Executing command on each change

### ISSUE THREAD

**Issue by ishergin** [criteo/consul-templaterb#64]
consul-templaterb has option for run permanent process:
> -e, --exec=<command>             Execute the following command

but some cases requires run command on template changing, e.g. `rndc reload` 

Now I have to write wrapper like:
```shell
#! /bin/sh

cleanup() {
	 rndc reload <zone>
}

trap "cleanup" INT

while true
do
	sleep 1
done
```
Could you add option for running command on template changing with interval `--wait=<min_duration>` ? Or are there other possibilites for it?

**Comment by pierresouchay** [comment]
Both are supported:

https://github.com/criteo/consul-templaterb#generate-multiple-templates

consul-templaterb --template "mytemplate.zone.erb:myzone.zone:/usr/bin/reload_zone myzone.zone"`
=> would execute /usr/bin/reload_zone myzone.zone each time the file does change

The option -w does what you need (at least n seconds between 2 changes): `-w, --wait=<min_duration>   `

**Comment by ishergin** [comment]
thanks!)
