### ISSUE TITLE
Get checks by state

### ISSUE THREAD

**Issue by jeromegn** [criteo/consul-templaterb#65]
Endpoint: https://www.consul.io/api-docs/health#list-checks-in-state

By using the `any` state, it's possible to watch all checks with a single query.

Unless you don't recommend using this? Perhaps per-node/service is less demanding since it changes less often?

**Comment by pierresouchay** [comment]
Hello @jeromegn,

Yes, this endpoint is nice, but has a few drawbacks:
 - it does not allow to list services (see this discussion for instance in https://github.com/hashicorp/consul/pull/7384 )
 - its output might be huge and change every ms in large clusters (in our case, it would be changing all the time)

What is exactly you use-case?

It really depends on what you want to do, I suspect some might use it in an interesting way, but I had no use for it now. If you want to do a PR to support it, I would be glad to help you implement it, however (see https://github.com/criteo/consul-templaterb/blob/master/lib/consul/async/consul_template.rb#L142 for example, implementation is straightforward)

**Comment by jeromegn** [comment]
I can work around it! Getting checks per node works for me.

Our use case is our global load balancer. We're currently manually querying Consul at runtime, but I'm now exploring generating the config outside of it. We're sometimes pulling 1 Gbps between our consul servers and clients...

We need to know about every service across all datacenters (our setup currently has a single "global" datacenter) and their health status. I'm fetching all services for each node, then all checks for the node. For each service I then select all checks that match its ID and manually instantiate a `Consul::Async::ServiceInstance` to use the `status` method and figure out if the service is healthy.

Do you have a public chat room, forum or some other place to discuss? I don't have any issues right now, but I found this project when reading consul issues and noticed you had issues similar to ours. Would be interesting to chat!

**Comment by pierresouchay** [comment]
No, it is far easier than that, have a look in samples, you can for instance check the HaProxy configuration examples, you can just use templates, it will work nicely, no real code to do.

**Comment by pierresouchay** [comment]
I'll be glad to exchange, drop me a msg on Twitter (@vizionr), I'll send you my address

**Comment by pierresouchay** [comment]
I'll be glad to exchange, drop me a msg on Twitter (@vizionr), I'll send you my personal address

**Comment by pierresouchay** [comment]
@jeromegn I would start how much bandwith uses this template on your cluster: https://github.com/criteo/consul-templaterb/blob/master/samples/all_services.txt.erb

**Comment by pierresouchay** [comment]
Fixed by https://github.com/criteo/consul-templaterb/commit/d8674121baf91883b4f5be1537b4b8ba478f9cc1 and released in version 1.27.0
