### ISSUE TITLE
Correct usage of --wait-signal option

### ISSUE THREAD

**Issue by jlkiri** [criteo/consul-templaterb#91]
Thanks for this wonderful tool. This is my first time using it so I would like an advice.

My understanding of ` --wait-signal=n` option is that `consul-templaterb` waits n seconds before sending the signal defined in `--sig-reload` to the long-running `--exec` proccess. However what I see is that the signal is sent immediately after Consul service data changes. For example I'm using Nomad for spawning tasks and registrating them and as soon as I tell Nomad to run or stop tasks the signal is sent to my other process. Am I wrong or is there a bug here?

The command:
```
consul-templaterb --template "members.json.erb:members.json" \
  --consul-addr=127.0.0.1:8500 --sig-reload USR1 --wait-signal 5 --exec=myctl
```

**Comment by pierresouchay** [comment]
Nope, not exactly:

```
    -W, --wait-signal=min_duration   Wait at least n seconds before each reload signal being sent to next --exec process
```

If your file changes every 2 seconds and you put `--wait-signal 5` => it means your program will receive a signal every 60 seconds, not every 2 seconds. However, the first signal will likely be sent immediately, but the next one will be sent after 5 seconds at the minimum, even if the file was generated 2 times in the 5 seconds interval.

It is intended for configuration that are changing too much -> you don't want to reload every 2 seconds, but you want your program to be at the maximum 1 min late for instance (`--wait-signal 60`)

**Comment by jlkiri** [comment]
Ok, I see, thank you!
